# Site settings
title: "Melvyn de Kort"
email: melvyn@dekort.dev
description: "Melvyn's website and blog"
baseurl: ""
url: "https://melvyndekort.github.io/"
title_description: |
  Cloud Architect, Cloud Engineer, Software Developer, Docker enthusiast.<br/>
  <br/>
  My goal is to combine all of my skills to complete the tasks at hand and do so in a DevOps environment.<br/>
  <br/>
  Skills: DevOps, AWS, Terraform, Networking, Linux, Docker, Java and SQL.
title_image: "https://www.gravatar.com/avatar/bd311a330c06553cba590c582d5130ab?s=500&d=mm"
google_analytics: "UA-139724189-1"
disqus_account: 
github_repository: https://github.com/melvyndekort/melvyndekort.github.io
addthis_id: 
post_limit: 5

# Social usernames/URLs
twitter_username: melvyndekort
github_username:  melvyndekort
instagram_username: melvyndekort
reddit_username: melvyndekort
linkedin_link: https://www.linkedin.com/in/melvyndekort/

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
